# main properties
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: ${SPRING_REDIS_HOST:dev.metabuild.org}
    port: ${SPRING_REDIS_PORT:6379}
  session:
    store-type: redis
sandbox:
  api:
    uri: http://dev.metabuild.org:8080
    scheme: http
    host: ${SANDBOX_API_HOST:dev.metabuild.org}
    port: ${SANDBOX_API_PORT:8080}
    endpoints:
      authorization: /auth
      registration: /register
      users: /users
      tasks: /tasks
