# main properties
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
sandbox:
  api:
    uri: http://dev.metabuild.org:8080
    scheme: http
    host: ${SANDBOX_API_HOST:dev.metabuild.org}
    port: 8080
    endpoints:
      authorization: /auth
      users: /users
      tasks: /tasks
  admin:
    username: ${SANDBOX_ADMIN_USERNAME:admin@metabuild.org}
    password: ${SANDBOX_ADMIN_PASSWORD:Passw0rd}
  user:
    username: ${SANDBOX_TEST_USERNAME:test@metabuild.org}
    password: ${SANDBOX_TEST_PASSWORD:test}
