version: '3'
networks:
  metabuild:

services:
  redis:
    image: redis:alpine
    hostname: redis
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      metabuild:
        aliases:
          - redis.metabuild.org

  database:
    image: mysql
    hostname: database
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: sandbox_api
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: Passw0rd
    networks:
      metabuild:
        aliases:
          - database.metabuild.org

  auth:
    image: gcr.io/spring-sandbox-219017/sandbox-auth
    hostname: auth
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      SANDBOX_DATABASE_HOST: database.metabuild.org
      SANDBOX_DATABSE_PORT: 3306
    networks:
      metabuild:
        aliases:
          - auth.metabuild.org

  api:
    image: gcr.io/spring-sandbox-219017/sandbox-api
    hostname: api
    depends_on:
      - auth
    ports:
      - 8081:8081
    environment:
      SANDBOX_DATABASE_HOST: database.metabuild.org
      SANDBOX_DATABSE_PORT: 3306
    networks:
      metabuild:
        aliases:
          - api.metabuild.org

  frontend:
    image: gcr.io/spring-sandbox-219017/sandbox-frontend
    hostname: frontend
    depends_on:
      - auth
      - api
      - redis
    environment:
      SANDBOX_API_HOST: api.metabuild.org
      SANDBOX_API_PORT: 8081
      SPRING_REDIS_HOST: redis.metabuild.org
      SPRING_REDIS_PORT: 6379
    ports:
      - 8082:8082
    networks:
      metabuild:
        aliases:
          - frontend.metabuild.org
    extra_hosts:
      - "dev.metabuild.org:127.0.0.1"
