version: '3'
services:
  api:
    image: gcr.io/spring-sandbox-219017/sandbox-api
    hostname: api
    ports:
      - "8080:8080"
  frontend:
    image: gcr.io/spring-sandbox-219017/sandbox-frontend
    hostname: frontend
    depends_on:
      - api
      - redis
    environment:
      - SANDBOX_API_HOST=api
      - SPRING_REDIS_HOST=redis
    ports:
      - "8081:8081"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
