# DEFAULT PROPERTIES
server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox_api
    username: sandbox
    password: ${SANDBOX_ADMIN_PASSWORD:Passw0rd}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      jadira:
        usertype:
          autoRegisterUserTypes: true
    hibernate:
      ddl-auto: create
    show-sql: true
sandbox:
  admin:
    username: ${SANDBOX_ADMIN_USERNAME:admin@metabuild.org}
    password: ${SANDBOX_ADMIN_PASSWORD:Passw0rd}
  user:
    username: ${SANDBOX_TEST_USERNAME:test@metabuild.org}
    password: ${SANDBOX_TEST_PASSWORD:test}
