# DEFAULT PROPERTIES
server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
spring:
  cache:
    type: simple
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
