# PRODUCTION PROPERTIES
server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
spring:
  datasource:
    url: jdbc:h2:~/.sandbox;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jadira:
        usertype:
          autoRegisterUserTypes: true
    hibernate:
      ddl-auto: create
  cache:
    type: simple
