# DEFAULT PROPERTIES
server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
spring:
  cache:
    type: simple
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  datasource:
    url: jdbc:h2:~/.sandbox;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jadira:
        usertype:
          autoRegisterUserTypes: true
    hibernate:
      ddl-auto: create
    show-sql: true
sandbox:
  admin:
    username: ${SANDBOX_ADMIN_USERNAME:admin@metabuild.org}
    password: ${SANDBOX_ADMIN_PASSWORD:Passw0rd}
  user:
    username: ${SANDBOX_TEST_USERNAME:test@metabuild.org}
    password: ${SANDBOX_TEST_PASSWORD:test}
