# DEFAULT PROPERTIES
server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
spring:
  #  security:
  #    user:
  #      name: user
  #      password: test
  cache:
    type: simple
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
security:
  oauth2:
    client:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
      access-token-uri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      user-info-uri: https://www.googleapis.com/userinfo/v2/me
      prefer-token-info: false
